---
- name: Server
  hosts: "{{ var_host | default('server') }}"
  vars:
    codename: "{{ ansible_lsb.codename }}"
    username: "leaf"
  gather_facts: true
  roles:
    - role: core_cli
      tags: core_cli
    - role: sudo
      tags: sudo
    - role: qemu_agent
      tags: qemu_agent
    - role: net_tools
      tags: net_tools
    - role: docker
      tags: docker
