set-option -g default-shell /usr/bin/fish
set-option -sa terminal-overrides ",xterm*:Tc"

bind-key -n 'C-k' 'send-keys C-k'
bind-key -n 'C-l' 'send-keys C-l'

setw -g mouse on

set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'christoomey/vim-tmux-navigator'
#set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @emulate-scroll-for-no-mouse-alternate-buffer "on"

run '~/.tmux/plugins/tpm/tpm'

