---
- name: Check if i386 architecture is enabled
  ansible.builtin.shell: dpkg --print-foreign-architectures | grep -q i386
  register: i386_check
  failed_when: false
  changed_when: false

- name: Enable i386 architecture
  ansible.builtin.command: dpkg --add-architecture i386
  when: i386_check.rc != 0
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: i386_check.rc != 0
  become: true

- name: Install steam-installer and related packages
  ansible.builtin.apt:
    name:
      - steam-installer
      - mesa-vulkan-drivers
      - libglx-mesa0:i386
      - mesa-vulkan-drivers:i386
      - libgl1-mesa-dri:i386
    state: present
  become: true