---
- name: Create ssh directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    mode: "0700"

- name: Generate ed25519 ssh key
  community.crypto.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_ed25519"
    type: ed25519
    comment: "{{ username }}@{{ ansible_hostname }}"
    mode: "0600"
    regenerate: never
