---
- name: Install Apt Repositories
  ansible.builtin.include_tasks: repos.yml

- name: Flush handlers
  meta: flush_handlers

- name: Install CLI software
  ansible.builtin.include_tasks: cli.yml

- name: Install GUI software
  ansible.builtin.include_tasks: gui.yml

- name: Install Network Manager plugins
  ansible.builtin.include_tasks: network.yml

- name: Configure software
  ansible.builtin.include_tasks: config.yml

- name: Install GNOME extensions
  ansible.builtin.include_tasks: gnome-extensions.yml
