# vim:fileencoding=utf-8:foldmethod=marker

kitty +kitten themes --reload-in=all macchiato.conf

# The basic colors
foreground              #CAD3F5
background              #24273A
selection_foreground    #24273A
selection_background    #F4DBD6

# Cursor colors
cursor                  #F4DBD6
cursor_text_color       #24273A

# URL underline color when hovering with mouse
url_color               #F4DBD6

# Kitty window border colors
active_border_color     #B7BDF8
inactive_border_color   #6E738D
bell_border_color       #EED49F

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #181926
active_tab_background   #C6A0F6
inactive_tab_foreground #CAD3F5
inactive_tab_background #1E2030
tab_bar_background      #181926

# Colors for marks (marked text in the terminal)
mark1_foreground #24273A
mark1_background #B7BDF8
mark2_foreground #24273A
mark2_background #C6A0F6
mark3_foreground #24273A
mark3_background #7DC4E4

# The 16 terminal colors

# black
color0 #494D64
color8 #5B6078

# red
color1 #ED8796
color9 #ED8796

# green
color2  #A6DA95
color10 #A6DA95

# yellow
color3  #EED49F
color11 #EED49F

# blue
color4  #8AADF4
color12 #8AADF4

# magenta
color5  #F5BDE6
color13 #F5BDE6

# cyan
color6  #8BD5CA
color14 #8BD5CA

# white
color7  #B8C0E0
color15 #A5ADCB

font_family      ShureTechMono Nerd Font
font_size 14.0

cursor_shape block

mouse_hide_wait 3.0

remember_window_size  yes

enabled_layouts tall,stack

map ctrl+shift+enter launch --cwd=current --location=vsplit
map kitty_mod+x toggle_layout stack
map shift+left resize_window narrower
map shift+right resize_window wider
map shift+up resize_window taller
map shift+down resize_window shorter 3
map shift+home resize_window reset
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

tab_bar_edge bottom
tab_bar_style fade

shell /usr/bin/fish
shell_integration no-cursor
