---
- name: Install sudo
  ansible.builtin.apt:
    name:
      - sudo
    state: present
  become: true

- name: "Ensure wheel group exists"
  become: true
  ansible.builtin.group:
    name: wheel
    state: present

- name: "Add user to wheel group: {{ username }}"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wheel
    append: true

- name: "Grant wheel group sudo access"
  become: true
  community.general.sudoers:
    name: "wheel"
    group: "wheel"
    state: present
    commands: "ALL"
    validation: required
