---
- name: Install sudo
  ansible.builtin.apt:
    name:
      - sudo
    state: present
  become: true

- name: "Ensure sudo group exists"
  become: true
  ansible.builtin.group:
    name: sudo
    state: present

- name: "Add user to sudo group: {{ username }}"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: sudo
    append: true

- name: "Grant sudo group sudo access"
  become: true
  community.general.sudoers:
    name: "sudo"
    group: "sudo"
    state: present
    commands: "ALL"
    validation: required
